### ISSUE TITLE
not working anymore since MM v2.20.0 Upgrade

### ISSUE THREAD

**Issue by editwentyone** [AgP42/MMM-SmartWebDisplay#34]
hi,

I love your plugin but its not doing anything since I updated magic mirror to v2.20.0 

any idea how to debug that and to fix? :( 

would love to see it running again

**Comment by JWilson5607** [comment]
I just attempted to install it on mine - I am running the latest as well.  What error are you getting?  I am getting a refused to connect error, but am able to navigate directly to my page on the computer MM is running on.

![image](https://user-images.githubusercontent.com/82344713/181156851-fa9838d9-8c12-4eb7-b564-1f70d60e8b53.png)

**Comment by JWilson5607** [comment]
I checked my developer settings and it is the following error: Refused to display 'http://10.0.4.11:3001/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.  - I wonder if yours is the same issue or not.  I am not sure how to get around this just yet.

Fixed by allowing sameorigin for the docker container i was attempting to connect to

**Comment by editwentyone** [comment]
what did you do exactly? maybe I have the same problem, had to disable the plugin for now

**Comment by editwentyone** [comment]
@JWilson5607 could you guide what you did?

**Comment by johnwilson5607** [comment]
> @JWilson5607 could you guide what you did?

Apologies @editwentyone life got busy.  I will take a look at is this evening when I get back home and post what I did to fix it.  I believe, since I am using unraid as my docker host, that I just added another variable to the container in the menu, but what exactly it was I do not recall.

**Comment by JWilson5607** [comment]
@editwentyone https://github.com/louislam/uptime-kuma/issues/1146

See here.  I have spun up a docker-compose version as I am wanting uptime kuma over to my pi and not my Unraid box.  I am really green with docker and am trying to figure out how to add UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1 to the docker-compose.yml file.  So far no luck

**Comment by JWilson5607** [comment]
Correction - I had to completely restart the browser to show it after updating the docker-compose.yml file with this:

```
version: '3.3'

services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - ./uptime-kuma-data:/app/data
    ports:
      - 3001:3001  # <Host Port>:<Container Port>
    restart: always
    environment:
      - UPTIME_KUMA_DISABLE_FRAME_SAMEORIGIN=1

```
